name: MyFirstAction

on: [push, workflow_dispatch]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World !!"

      - name: Print GoodBye
        run: echo "Done - bye!"
  Deploy: 
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: deployment start
        run: echo "Deployment started...."
      - name: deployment completed
        run: echo "deployment completed"
  RunApplication:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Starting Application
        run: echo "Running Application"