name: MyFirstAction

on:
  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World !!"

      - name: Print GoodBye
        run: echo "Done - bye!"
