name: Test Job

on:
 workflow_dispatch:

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps: 
            - name: just chill
              run: echo "just chill"
            - name: print second job
              run: echo "printing second job"
